# -*- coding: utf-8 -*-
"""Bigdata_project_movies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x63hT0qvTDSOm5pN1ceOMwWzfL6nMlLt
"""

pip install boto3

pip install dynamodb-json

pip install requests

import boto3
import time 
import uuid 
from datetime import datetime  
from dynamodb_json import json_util as json 
from __future__ import print_function
import json
import decimal
import timeit
import requests
from google.colab import drive
from boto3.dynamodb.conditions import Key, Attr

AWS_ACCESS = ""
AWS_SECRET = ""
AWS_REGION = "us-east-2"
TABLE_NAME = "movies"

dynamodb_client = boto3.client('dynamodb',aws_secret_access_key=AWS_SECRET,aws_access_key_id=AWS_ACCESS,region_name=AWS_REGION)

#dynamodb = client.resource('dynamodb', region_name='us-east-2')
#didnt work I think
movies_table = dynamodb_client.create_table(TableName='movies',KeySchema=[{'AttributeName': 'movieId','KeyType': 'HASH'},{'AttributeName': 'userId','KeyType': 'RANGE'}],AttributeDefinitions=[{'AttributeName': 'movieId','AttributeType': 'N'},{'AttributeName': 'userId','AttributeType': 'N'},],ProvisionedThroughput={'ReadCapacityUnits': 10,'WriteCapacityUnits': 10 })

drive.mount("/content/drive")

movies="/content/drive/My Drive/movierating.json"
print(movies)

#Inserting bulk data into the table
count=0
dynamodb = boto3.resource('dynamodb', region_name='us-east-2',aws_secret_access_key=AWS_SECRET,aws_access_key_id=AWS_ACCESS)
table = dynamodb.Table('movies')



records=""
with open(movies, 'r') as datafile:
  records=json.load(datafile, parse_float = decimal.Decimal)

count=0
for i in records:
  response=table.put_item(Item=i)
  count+=1
  if count==500:
    break

#Putting Single Item into the table using PutItem
start = time.time()
mId = 5000
uId = 5
rating = 3
TS=1163373699

response = table.put_item(
   Item={
        'movieId': mId,
        'userId': uId,
        'rating': rating,
        'timestamp': TS
        }
)

end = time.time()
print(end - start)
print(response)

#scan
start = time.time()

response = table.scan()
data = response['Items']

while 'movieId' in response:
    response = table.scan(ExclusiveStartKey=response['movieId'])
    data.extend(response['Items'])

print(response)

end = time.time()
print(end - start)

#Getting Single Item from the table using GetItem
start = time.time()
mId = 2502
uId = 6


try:
    response = table.get_item(
        Key={
            'movieId': mId,
            'userId': uId
        }
    )

except (ClientError, KeyError) as e:
        print_(e)

print(response)
end = time.time()
print(end - start)

start = time.time()
response = table.query(
    KeyConditionExpression=Key('movieId').eq(2529)
)
print(response)
for i in response['Items']:
    print(i['movieId'], ":", i['userId'])
end = time.time()
print(end - start)

#filter
start = time.time()
response = table.scan(FilterExpression=Attr('userId').contains(6))

print(response)
end = time.time()
print(end - start)

#filter
start = time.time()
response = table.scan(FilterExpression=Attr('timestamp').gte(1109258257))
print(response)
for i in response['Items']:
    print(i['movieId'], ":", i['userId'])
end = time.time()
print(end - start)